#!/bin/bash
if [ ! "$(command -v docker)" ]; then
    echo "docker could not be found"
    exit 0}}

CURRENT_DIR=$(basename $(pwd))

NETWORK_NAME=mqtt-network

if [ ! "$(docker network ls | grep "$NETWORK_NAME")" ]; then
  echo "Creating network ..."
  docker network create $NETWORK_NAME
fi

docker run --rm -it \
    --name mon_mongo \
    -p 27017:27017 \
    --net $NETWORK_NAME \
    mongo:7.0.2